# -*- coding: utf-8 -*-
"""Matplotlib.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJAE8U6OGnTY5s1iwzHP_3N4JykHSTBq
"""

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np

def setup(ax, title):
    ax.yaxis.set_major_locator(ticker.NullLocator())
    ax.spines[['left', 'right', 'top']].set_visible(False)
    ax.xaxis.set_minor_locator(ticker.AutoMinorLocator(4))
    ax.xaxis.set_ticks_position('bottom')
    ax.tick_params(which='major', width=1.00, length=5)
    ax.tick_params(which='minor', width=0.75, length=2.5)
    ax.set_xlim(0, 5)
    ax.set_ylim(0, 1)
    ax.text(0.0, 0.2, title, transform=ax.transAxes,
            fontsize=14, fontname='Monospace', color='tab:blue')

fig = plt.figure(figsize=(8, 8), layout='constrained')
fig0, fig1, fig2 = fig.subfigures(3, height_ratios=[1.5, 1.5, 7.5])

fig0.suptitle('Форматирование строк', x=0, ha='left')
ax0 = fig0.subplots()
setup(ax0, "'Отображение в км'")
ax0.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f км'))

fig1.suptitle('Форматирование функций', x=0, ha='left')
ax1 = fig1.subplots()
setup(ax1, 'def(x, pos): return str(x-5)')
ax1.xaxis.set_major_formatter(lambda x, pos: str(x-5))

fig2.suptitle('Formatter Object Formatting', x=0, ha='left')
ax2 = fig2.subplots(7, 1)
setup(ax2[0], 'NullFormatter()')
ax2[0].xaxis.set_major_formatter(ticker.NullFormatter())

setup(ax2[1], 'StrMethodFormatter("{x:.3f}")')
ax2[1].xaxis.set_major_formatter(ticker.StrMethodFormatter("{x:.3f}"))

setup(ax2[2], 'FormatStrFormatter("#%d")')
ax2[2].xaxis.set_major_formatter(ticker.FormatStrFormatter("#%d"))

setup(ax2[3], 'FixedFormatter(["A", "B", "C", "D", "E", "F"])')
ax2[3].xaxis.set_major_formatter(ticker.FixedFormatter(["A", "B", "C", "D", "E", "F"]))
ax2[3].xaxis.set_major_locator(ticker.FixedLocator([1, 2, 3, 4, 5, 6]))


setup(ax2[4], 'ScalarFormatter()')
ax2[4].xaxis.set_major_formatter(ticker.ScalarFormatter(useMathText=True))

setup(ax2[5], 'PercentFormatter(xmax=5)')
ax2[5].xaxis.set_major_formatter(ticker.PercentFormatter(xmax=5))

plt.show()

import matplotlib.pyplot as plt, matplotlib.patches as pat
plt.xlim(-2, 2)
plt.ylim(-2, 2)
axes = plt.gca()
axes.set_aspect('equal')
fig1 = pat.Rectangle((-1.5, -1.5), 3, 3, color='green', alpha=0.5)
fig2 = pat.Rectangle((-1, -1), 2, 2, color='green')
axes.add_patch(fig1)
axes.add_patch(fig2)
plt.title('color = green')
plt.grid(True)
plt.show()